name: action-wait-for-api

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - name: action-wait-for-api
        uses: ./ # Uses an action in the root directory
        with:
          timeout: "20"
          interval: "5"
          url: "https://api.fabscale.cc/v1/status"
          expected-response-field: "status"

  node-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
